version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    container_name: cm
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_DATABASE: cm